web:
  image: nginx:latest
  ports:
    - "8082:80"
  volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  environment:
    - TZ=Europe/Amsterdam
php:
  build: php7-fpm
  volumes:
    - ./code:/code
  links:
    - mariadb
    - redis
  environment:
    - TZ=Europe/Amsterdam
mariadb:
  image: mariadb:latest
  ports:
    - "3307:3306"
  volumes:
    - "./data:/var/lib/mysql"
  environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=1
    - MYSQL_USER=trafficlink
    - MYSQL_PASSWORD=trafficlink
    - MYSQL_DATABASE=trafficlink
    - TZ=Europe/Amsterdam
redis:
  image: redis:latest
  environment:
    - TZ=Europe/Amsterdam
